Request to adding UML diagram
ViRGiL175/git-starship pull request #9
Opened 2017-03-19 18:27 UTC by AlexRakitskiy

- Class architecture UML  248b40f
- Added UML diagram classes  871e7da
- UML class architecture  8c375b8
- Fixed some UML classes  bd91419

2017-03-19 18:46 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +void lose();
`winState()`, `loseState()`

2017-03-19 18:47 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        -HashMap<String, IStorageable> storage
storage?

2017-03-19 18:48 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +void add(String itemName);
Add by `itemName`?

2017-03-19 18:49 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +    class Storage {
`get()` method?

2017-03-19 18:53 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +int getHitPoints();
Where are hit points?

2017-03-19 18:55 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        abstract class Starship implements IAttackable {
Battle cycle.

2017-03-19 18:58 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +String getName();
Where are names?

2017-03-19 19:01 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +    package ammunition {
Why ammunition isn't `IStorageable`

2017-03-19 19:03 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +            #int baseDamage;
Just `damage`?

2017-03-19 19:03 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +            -int baseDamage;
`damageIncreasing` maybe?

2017-03-19 19:07 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +enum AmmoType {
Shit

2017-03-19 19:08 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +abstract class Event {
Constructor?

2017-03-19 19:11 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +    interface ILandable {
Mindless?

2017-03-19 19:12 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +            -int cash;
Where is storage?!

2017-03-19 19:13 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        class BaseTrader extends Trader {
Why 'base'?

2017-03-19 19:14 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +            +void trade();
WTF?!!!

2017-03-19 19:15 UTC, ViRGiL175 requested changes
- Fixes
- Commits messages (description details)

2017-03-19 19:28 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +            +void trade();
Fixed!

2017-03-19 19:28 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +        class BaseTrader extends Trader {
Fixed!

2017-03-19 19:28 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +            -int cash;
Fixed!

2017-03-19 19:42 UTC, AlexRakitskiy commented on src/main/resources/diagram_git_starship.puml
> +            -int baseDamage;
Fixed

2017-03-19 19:42 UTC, AlexRakitskiy commented on src/main/resources/diagram_git_starship.puml
> +            #int baseDamage;
Fixed

2017-03-19 19:42 UTC, AlexRakitskiy commented on src/main/resources/diagram_git_starship.puml
> +    package ammunition {
Fixed

2017-03-19 19:43 UTC, AlexRakitskiy commented on src/main/resources/diagram_git_starship.puml
> +        +String getName();
Fixed

2017-03-19 19:43 UTC, AlexRakitskiy commented on src/main/resources/diagram_git_starship.puml
> +        +enum AmmoType {
Fixed

2017-03-19 19:47 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +        -HashMap<String, IStorageable> storage
Fixed!

2017-03-19 19:47 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +        +void lose();
Fixed!

2017-03-19 19:53 UTC, AlexRakitskiy commented on src/main/resources/diagram_git_starship.puml
> +    interface ILandable {
Fixed

2017-03-19 19:53 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +        +int getHitPoints();
Fixed!

2017-03-19 19:54 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +        +String getName();
Fixed!

2017-03-19 20:00 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +        +void add(String itemName);
Fixed!

2017-03-19 20:01 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +    class Storage {
Fixed!

2017-03-20 15:10 UTC, AlexRakitskiy commented on src/main/resources/diagram_git_starship.puml
> +        abstract class Starship implements IAttackable {
Fixed

2017-03-20 18:55 UTC, AlexRakitskiy commented
Changes done

2017-03-20 19:21 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +void lose();
It is not fixed in last commit (49337ec9bd6e7fe8582bf00650133d44e242ae2b). @Alvahaze

2017-03-20 19:55 UTC, ViRGiL175 requested changes
- Where is loot and different tradable stuff?
- Where are constructors? Especially in `Event`, `Starship` classes. It is a possible NPE in future.
- Confusing `Battle` class

Nice progress anyway.

2017-03-20 19:55 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +void win();
It is not fixed. Why?

2017-03-20 19:55 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +            +IStoregable getFromStorage(String iStoregableName);
"Storageable" or "storable" maybe?

http://www.dictionary.com/browse/storable

2017-03-20 19:55 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        -int capacity;
Fields should be in top of class body.

2017-03-20 19:55 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +            +void sell(int cash, String itemName);
Maybe make these methods should return `boolean`?

Why void?

2017-03-20 19:55 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +            +void upgrade(int cash, String itemName);
Maybe `boolean` too?

In case of lack of money etc?

2017-03-20 19:55 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +abstract class Event {
Possible NPE (`NullPointerException`) for `universe`. Class _should_ have `universe` for callbacks.

2017-03-20 19:55 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +        +class Battle {
Very stupid class.

Possible NPE for `gitStarship`, NPE for `universe` etc.

What is purpose of this class?

2017-03-20 19:55 UTC, ViRGiL175 commented on src/main/resources/diagram_git_starship.puml
> +            -ArrayList<Starship> ships;
Why there are no possibility to find storage in open space?

It can be a pieces of blown Starship or life-saving capsule etc.

2017-03-20 20:15 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +        -int capacity;
Fixed

2017-03-20 20:18 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +            +void sell(int cash, String itemName);
Fixed!

2017-03-20 20:18 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +            +void upgrade(int cash, String itemName);
Fixed!

2017-03-20 20:21 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +            -ArrayList<Starship> ships;
Fixed!

2017-03-20 20:38 UTC, ghost commented on src/main/resources/diagram_git_starship.puml
> +        +abstract class Event {
Fixed!

2017-03-20 20:53 UTC, Alvahaze commented on src/main/resources/diagram_git_starship.puml
> +        +class Battle {
Fixed!

2017-03-21 06:45 UTC, closed without merging